In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
import numpy as np
a_dict={'1st':1, '2nd':3, '3rd':5, '4th':7}
ser=pd.Series(a_dict)
ser

1st    1
2nd    3
3rd    5
4th    7
dtype: int64

## ðŸŽ¯ Your Task:

Using **Pandas Series**, perform the following:

âœ… Create a Series named `scores` using the dictionary `student_scores`.

âœ… Print the marks scored by **"Charlie"** and **"Eva"**.

âœ… Add **5 bonus marks** to all students and print the updated Series.

âœ… Display only the students who scored **above 90** after the bonus.

âœ… Calculate and print the **average marks** of the class (after the bonus).

In [ ]:
import pandas as pd
import numpy as np
student_scores={'charlie':70, 'eva':75, 'alice':90, 'bob':72}
scores=pd.Series(student_scores)
print(scores['charlie'],scores['eva'])
scores=scores+5
print("Added 5 bonus marks to all students")
print("Updated scores:")
print(scores)
print("Students who scored above 90 after bonus:",scores[scores>90])
print("Average marks of students:",np.mean(scores))

70 75
Added 5 bonus marks to all students
Updated scores:
charlie    75
eva        80
alice      95
bob        77
dtype: int64
Students who scored above 90 after bonus: alice    95
dtype: int64
Average marks of students: 81.75

In [ ]:
import pandas as pd
import numpy as np
an_array=np.array([[25,85],[25,90],[26,70],[24,80]])
ser=pd.DataFrame(an_array,
                 index=['alice','bob','chirs','eva'],
                 columns=['age','marks'])
ser
print("values of the dataframe:",ser.values)
print("index of the dataframe:",ser.index)
print("columns of the dataframe:",ser.columns)

values of the dataframe: [[25 85]
 [25 90]
 [26 70]
 [24 80]]
index of the dataframe: Index(['alice', 'bob', 'chirs', 'eva'], dtype='object')
columns of the dataframe: Index(['age', 'marks'], dtype='object')

In [ ]:
 import pandas as pd
 a_dict={'name':{'ru':'rukshan','pr':'prasad','gi':'giya','ha':'hasini'},
         'age':{'ru':25,'pr':25,'gi':26,'ha':22},
         'marks':{'ru':85,'pr':90,'gi':96,'ha':82}}
df=pd.DataFrame(a_dict)
df

       name  age  marks
ru  rukshan   25     85
pr   prasad   25     90
gi     giya   26     96
ha   hasini   22     82

In [ ]:
 import pandas as pd
 print("DataFrame creation: Using Dictionaries and lists")
 a_dict={'name':['rukshan','prasad','giya','hasini'],
         'age':[25,25,26,22],
         'marks':[85,90,96,82]}
df=pd.DataFrame(a_dict)
print(df)
print(df.index)
print(df.values)
print(df.columns)
print(df.shape)
print(df.size)
print(df.dtypes)
print(df.values.ndim)
print(df.values.shape)

DataFrame creation: Using Dictionaries and lists
      name  age  marks
0  rukshan   25     85
1   prasad   25     90
2     giya   26     96
3   hasini   22     82
RangeIndex(start=0, stop=4, step=1)
[['rukshan' 25 85]
 ['prasad' 25 90]
 ['giya' 26 96]
 ['hasini' 22 82]]
Index(['name', 'age', 'marks'], dtype='object')
(4, 3)
12
name     object
age       int64
marks     int64
dtype: object
2
(4, 3)

In [ ]:
import pandas as pd
print("DataFrame creation: Using Dictionaries of series")
ser1=pd.Series(['rukshan','prasad','giya','hasini'],index=['ru','pr','gi','hs'])
ser2=pd.Series([25,25,26,22],index=['ru','pr','gi','hs'])
ser3=pd.Series([85,90,96,82],index=['ru','pr','gi','hs'])
a_dict={'name':ser1,
        'age':ser2,
        'marks':ser3}

df=pd.DataFrame(a_dict)
df

DataFrame creation: Using Dictionaries of series

       name  age  marks
ru  rukshan   25     85
pr   prasad   25     90
gi     giya   26     96
hs   hasini   22     82


You are given three Series representing student data:

Names of students

Their ages

Their marks

These series are combined into a DataFrame as shown earlier.

### ðŸŽ¯ Your Task:
Using the existing DataFrame, perform the following operations:

âœ… Print the details (name, age, marks) of the student who scored the highest marks.

âœ… Add a new student "Tharushi" with age 23 and marks 88 using the index "Th".

âœ… Display the details of students who are 25 years old or older.

âœ… Increase the marks of students below 80 by 10 bonus points.

âœ… Calculate and print the average marks of all students after the bonus.

In [ ]:
import pandas as pd
ser1=pd.Series(['rukshan','prasad','giya','hasini'],index=['ru','pr','gi','hs'])
ser2=pd.Series([25,25,26,22],index=['ru','pr','gi','hs'])
ser3=pd.Series([85,90,96,82],index=['ru','pr','gi','hs'])
a_dict={'name':ser1,
        'age':ser2,
        'marks':ser3}

df=pd.DataFrame(a_dict)
df
highest = df[df['marks'] == df['marks'].max()]
print("Student with the highest marks:\n", highest)
print("\n")
df.loc['Th'] = ['Tharushi', 23, 88]
print("After adding Tharushi:\n", df)
print("\n")
older_students = df[df['age'] >= 25]
print("Students aged 25 or older:\n", older_students)
print("\n")
df.loc[df['marks'] < 80, 'marks'] += 10
print("After giving 10 bonus marks to students below 80:\n", df)
print("\n")
average_marks = df['marks'].mean()
print(f"Average marks after adding bonus: {average_marks:.2f}")

Student with the highest marks:
     name  age  marks
gi  giya   26     96


After adding Tharushi:
         name  age  marks
ru   rukshan   25     85
pr    prasad   25     90
gi      giya   26     96
hs    hasini   22     82
Th  Tharushi   23     88


Students aged 25 or older:
        name  age  marks
ru  rukshan   25     85
pr   prasad   25     90
gi     giya   26     96


After giving 10 bonus marks to students below 80:
         name  age  marks
ru   rukshan   25     85
pr    prasad   25     90
gi      giya   26     96
hs    hasini   22     82
Th  Tharushi   23     88


Average marks after adding bonus: 88.20

In [ ]:
from google.colab import drive
import pandas as pd

#Mount your Drive
drive.mount('/content/drive')

#once mounted,navigate to the folder
#example path(adjust bsed on your structure)
path='/content/drive/My Drive/Colab Notebooks/data.csv'

df=pd.read_csv(path)
print(df.head())

Mounted at /content/drive
   Duration        Date  Pulse  Maxpulse  Calories
0        60  2020/12/01    110       130     409.1
1        60  2020/12/02    117       145     479.0
2        60  2020/12/03    103       135     340.0
3        45  2020/12/04    109       175     282.4
4        45  2020/12/05    117       148     406.0

In [ ]:
print(df.info())
print(df.isnull())
print(df.isnull().sum())

#to drop the na values
new_df=df.dropna()
print(new_df.to_string())

#to fill the na values
df.fillna(130,inplace=True)
print(df)

#na with median
x=df["Calories"].median()
df.fillna({"Calories":x},inplace=True)
print("\n")
print(df)

#na with mode
x=df["Calories"].mode()
df.fillna({"Calories":x},inplace=True)
print("\n")
print(df)

#na with mean
x=df["Calories"].mean()
df.fillna({"Calories":x},inplace=True)
print("\n")
print(df)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      32 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  32 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB
None
    Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False     False
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False  False  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False     False
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False
Duration    0
Date        0
Pulse       0
Maxpulse    0
Calories    0
dtype: int64
    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         130    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0
    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         130    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0


    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         130    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0


    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         130    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0


    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130     409.1
1         60  2020/12/02    117       145     479.0
2         60  2020/12/03    103       135     340.0
3         45  2020/12/04    109       175     282.4
4         45  2020/12/05    117       148     406.0
5         60  2020/12/06    102       127     300.0
6         60  2020/12/07    110       136     374.0
7        450  2020/12/08    104       134     253.3
8         30  2020/12/09    109       133     195.1
9         60  2020/12/10     98       124     269.0
10        60  2020/12/11    103       147     329.3
11        60  2020/12/12    100       120     250.7
12        60  2020/12/12    100       120     250.7
13        60  2020/12/13    106       128     345.3
14        60  2020/12/14    104       132     379.3
15        60  2020/12/15     98       123     275.0
16        60  2020/12/16     98       120     215.2
17        60  2020/12/17    100       120     300.0
18        45  2020/12/18     90       112     130.0
19        60  2020/12/19    103       123     323.0
20        45  2020/12/20     97       125     243.0
21        60  2020/12/21    108       131     364.2
22        45         130    100       119     282.0
23        60  2020/12/23    130       101     300.0
24        45  2020/12/24    105       132     246.0
25        60  2020/12/25    102       126     334.5
26        60  2020/12/26    100       120     250.0
27        60  2020/12/27     92       118     241.0
28        60  2020/12/28    103       132     130.0
29        60  2020/12/29    100       132     280.0
30        60  2020/12/30    102       129     380.3
31        60  2020/12/31     92       115     243.0

In [ ]:
from google.colab import drive
import pandas as pd

#Mount your Drive
drive.mount('/content/drive')

#once mounted,navigate to the folder
#example path(adjust bsed on your structure)
path='/content/drive/My Drive/Colab Notebooks/data.csv'

df=pd.read_csv(path)

print(df.info())
print(df.isnull())
print(df.isnull().sum())

#to fill the na values
#df.fillna(130,inplace=True)
#print(df)

#na with median
#x=df["Calories"].median()
#df.fillna({"Calories":x},inplace=True)
#print("\n")
#print(df)

#na with mode
#x=df["Calories"].mode()
#df.fillna({"Calories":x},inplace=True)
#print("\n")
#print(df)

#na with mean
x=df["Calories"].mean()
df.fillna({"Calories":x},inplace=True)
print("\n")
print(df)

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  32 non-null     int64
 1   Date      31 non-null     object
 2   Pulse     32 non-null     int64
 3   Maxpulse  32 non-null     int64
 4   Calories  30 non-null     float64
dtypes: float64(1), int64(3), object(1)
memory usage: 1.4+ KB
None
    Duration   Date  Pulse  Maxpulse  Calories
0      False  False  False     False     False
1      False  False  False     False     False
2      False  False  False     False     False
3      False  False  False     False     False
4      False  False  False     False     False
5      False  False  False     False     False
6      False  False  False     False     False
7      False  False  False     False     False
8      False  False  False     False     False
9      False  False  False     False     False
10     False  False  False     False     False
11     False  False  False     False     False
12     False  False  False     False     False
13     False  False  False     False     False
14     False  False  False     False     False
15     False  False  False     False     False
16     False  False  False     False     False
17     False  False  False     False     False
18     False  False  False     False      True
19     False  False  False     False     False
20     False  False  False     False     False
21     False  False  False     False     False
22     False   True  False     False     False
23     False  False  False     False     False
24     False  False  False     False     False
25     False  False  False     False     False
26     False  False  False     False     False
27     False  False  False     False     False
28     False  False  False     False      True
29     False  False  False     False     False
30     False  False  False     False     False
31     False  False  False     False     False
Duration    0
Date        1
Pulse       0
Maxpulse    0
Calories    2
dtype: int64


    Duration        Date  Pulse  Maxpulse  Calories
0         60  2020/12/01    110       130    409.10
1         60  2020/12/02    117       145    479.00
2         60  2020/12/03    103       135    340.00
3         45  2020/12/04    109       175    282.40
4         45  2020/12/05    117       148    406.00
5         60  2020/12/06    102       127    300.00
6         60  2020/12/07    110       136    374.00
7        450  2020/12/08    104       134    253.30
8         30  2020/12/09    109       133    195.10
9         60  2020/12/10     98       124    269.00
10        60  2020/12/11    103       147    329.30
11        60  2020/12/12    100       120    250.70
12        60  2020/12/12    100       120    250.70
13        60  2020/12/13    106       128    345.30
14        60  2020/12/14    104       132    379.30
15        60  2020/12/15     98       123    275.00
16        60  2020/12/16     98       120    215.20
17        60  2020/12/17    100       120    300.00
18        45  2020/12/18     90       112    304.68
19        60  2020/12/19    103       123    323.00
20        45  2020/12/20     97       125    243.00
21        60  2020/12/21    108       131    364.20
22        45         NaN    100       119    282.00
23        60  2020/12/23    130       101    300.00
24        45  2020/12/24    105       132    246.00
25        60  2020/12/25    102       126    334.50
26        60  2020/12/26    100       120    250.00
27        60  2020/12/27     92       118    241.00
28        60  2020/12/28    103       132    304.68
29        60  2020/12/29    100       132    280.00
30        60  2020/12/30    102       129    380.30
31        60  2020/12/31     92       115    243.00

In [ ]:
from google.colab import drive
import pandas as pd

#once mounted,navigate to the folder
#example path(adjust bsed on your structure)
path='/content/drive/My Drive/Colab Notebooks/data.csv'

df=pd.read_csv(path)


df['Date']=pd.to_datetime(df['Date'],format='mixed')
print(df.to_string())
df.dropna(subset=['Date'],inplace=True)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
22        45        NaT    100       119     282.0
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [ ]:
df.loc[7,'Duration']=45
print(df.to_string())

for x in df.index:
  if df.loc[x,"Duration"]>120:
    df.drop(x,inplace=True)

print(df.duplicated())
df.drop_duplicates(inplace=True)

#Filtering
#filter:rows where pulse>110
high_pulse=df[df['Pulse']>110]
print(high_pulse)

#sorting
#sort by calories descending
sorted_df=df.sort_values(by='Calories',
                         ascending=False)
print(sorted_df)

    Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
18        45 2020-12-18     90       112       NaN
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
28        60 2020-12-28    103       132       NaN
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0
0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
31    False
dtype: bool
    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
4         45 2020-12-05    117       148     406.0
23        60 2020-12-23    130       101     300.0
    Duration       Date  Pulse  Maxpulse  Calories
1         60 2020-12-02    117       145     479.0
0         60 2020-12-01    110       130     409.1
4         45 2020-12-05    117       148     406.0
30        60 2020-12-30    102       129     380.3
14        60 2020-12-14    104       132     379.3
6         60 2020-12-07    110       136     374.0
21        60 2020-12-21    108       131     364.2
13        60 2020-12-13    106       128     345.3
2         60 2020-12-03    103       135     340.0
25        60 2020-12-25    102       126     334.5
10        60 2020-12-11    103       147     329.3
19        60 2020-12-19    103       123     323.0
17        60 2020-12-17    100       120     300.0
5         60 2020-12-06    102       127     300.0
23        60 2020-12-23    130       101     300.0
3         45 2020-12-04    109       175     282.4
29        60 2020-12-29    100       132     280.0
15        60 2020-12-15     98       123     275.0
9         60 2020-12-10     98       124     269.0
7         45 2020-12-08    104       134     253.3
11        60 2020-12-12    100       120     250.7
26        60 2020-12-26    100       120     250.0
24        45 2020-12-24    105       132     246.0
31        60 2020-12-31     92       115     243.0
20        45 2020-12-20     97       125     243.0
27        60 2020-12-27     92       118     241.0
16        60 2020-12-16     98       120     215.2
8         30 2020-12-09    109       133     195.1
18        45 2020-12-18     90       112       NaN
28        60 2020-12-28    103       132       NaN

In [ ]:
# Create another DataFrame with Date and Trainer name
trainer_df = pd.DataFrame({
    'Date': ['2020/12/01', '2020/12/02', '2020/12/03'],
    'Trainer': ['Alex', 'Jordan', 'Taylor']
})

# Convert 'Date' column in trainer_df to datetime format
trainer_df['Date'] = pd.to_datetime(trainer_df['Date'])

# Now merge
merged_df = pd.merge(df, trainer_df, on='Date', how='left')

print(merged_df)

## Group by Duration and Calculate Average Calories
### Groups the dataset by the Duration column (i.e., how long each activity lasted).
### For each unique Duration, it computes the average Calories burned.
### Returns a Series with Duration as the index and average Calories as values.


# Group by Duration and get average Calories
avg_calories_by_duration = df.groupby('Duration')['Calories'].mean()

# Group by Pulse range (bucketed)
df['PulseRange'] = pd.cut(df['Pulse'], bins=[100, 110, 120, 130, 140, 150, 180])
grouped_stats = df.groupby('PulseRange', observed=False).agg({
    'Calories': 'mean',
    'Maxpulse': 'max'
})

print(grouped_stats)

    Duration       Date  Pulse  Maxpulse  Calories Trainer
0         60 2020-12-01    110       130     409.1    Alex
1         60 2020-12-02    117       145     479.0  Jordan
2         60 2020-12-03    103       135     340.0  Taylor
3         45 2020-12-04    109       175     282.4     NaN
4         45 2020-12-05    117       148     406.0     NaN
5         60 2020-12-06    102       127     300.0     NaN
6         60 2020-12-07    110       136     374.0     NaN
7         45 2020-12-08    104       134     253.3     NaN
8         30 2020-12-09    109       133     195.1     NaN
9         60 2020-12-10     98       124     269.0     NaN
10        60 2020-12-11    103       147     329.3     NaN
11        60 2020-12-12    100       120     250.7     NaN
12        60 2020-12-13    106       128     345.3     NaN
13        60 2020-12-14    104       132     379.3     NaN
14        60 2020-12-15     98       123     275.0     NaN
15        60 2020-12-16     98       120     215.2     NaN
16        60 2020-12-17    100       120     300.0     NaN
17        45 2020-12-18     90       112       NaN     NaN
18        60 2020-12-19    103       123     323.0     NaN
19        45 2020-12-20     97       125     243.0     NaN
20        60 2020-12-21    108       131     364.2     NaN
21        60 2020-12-23    130       101     300.0     NaN
22        45 2020-12-24    105       132     246.0     NaN
23        60 2020-12-25    102       126     334.5     NaN
24        60 2020-12-26    100       120     250.0     NaN
25        60 2020-12-27     92       118     241.0     NaN
26        60 2020-12-28    103       132       NaN     NaN
27        60 2020-12-29    100       132     280.0     NaN
28        60 2020-12-30    102       129     380.3     NaN
29        60 2020-12-31     92       115     243.0     NaN
            Calories  Maxpulse
PulseRange
(100, 110]    323.72     175.0
(110, 120]    442.50     148.0
(120, 130]    300.00     101.0
(130, 140]       NaN       NaN
(140, 150]       NaN       NaN
(150, 180]       NaN       NaN

Data Correlations- Finding Relationships

A great aspect of the Pandas module is the corr() method.
The corr() method calculates the relationship between each column in your data set.

df.corr()

Note: The corr() method ignores "not numeric" columns.

                      Duration     Pulse         Maxpulse    Calories
  Duration  1.000000    -0.155408  0.009403      0.922721
  Pulse        -0.155408    1.000000   0.786535      0.025120
  Maxpulse  0.009403    0.786535   1.000000      0.203814
  Calories  0.922721    0.025120   0.203814      1.000000

The Result of the corr() method is a table with a lot of numbers that represents how well the relationship is between two columns.

The number varies from -1 to 1.

1 means that there is a 1 to 1 relationship (a perfect correlation), and for this data set, each time a value went up in the first column, the other one went up as well.

0.9 is also a good relationship, and if you increase one value, the other will probably increase as well.

-0.9 would be just as good relationship as 0.9, but if you increase one value, the other will probably go down.

0.2 means NOT a good relationship, meaning that if one value goes up does not mean that the other will.

What is a good correlation? It depends on the use, but I think it is safe to say you have to have at least 0.6 (or -0.6) to call it a good correlation.

Perfect Correlation:
We can see that "Duration" and "Duration" got the number 1.000000, which makes sense, each column always has a perfect relationship with itself.

Good Correlation:
"Duration" and "Calories" got a 0.922721 correlation, which is a very good correlation, and we can predict that the longer you work out, the more calories you burn, and the other way around: if you burned a lot of calories, you probably had a long work out.

Bad Correlation:
"Duration" and "Maxpulse" got a 0.009403 correlation, which is a very bad correlation, meaning that we can not predict the max pulse by just looking at the duration of the work out, and vice versa.

In [ ]:
# Create the Trainer DataFrame
trainer_df = pd.DataFrame({
    'Date': ['2020/12/01', '2020/12/02', '2020/12/03'],
    'Trainer': ['Alex', 'Jordan', 'Taylor']
})

# Convert date to datetime
trainer_df['Date'] = pd.to_datetime(trainer_df['Date'])

# Merge with main df
df = pd.merge(df, trainer_df, on='Date', how='left')

# Fill missing trainers if needed
df['Trainer'].fillna('Unknown', inplace=True)

# Now this will work
#df.value_counts() for frequency distribution
print(df['Trainer'].value_counts())

#Renaming columns(rename()):
df.rename(columns={'Maxpulse':'Max_Pulse'},inplace=True)
df

#df.describe() for summary stats
print(df.describe())

Trainer
Unknown    27
Alex        1
Jordan      1
Taylor      1
Name: count, dtype: int64
        Duration                 Date       Pulse   Max_Pulse    Calories
count  30.000000                   30   30.000000   30.000000   28.000000
mean   56.000000  2020-12-15 19:12:00  103.733333  129.100000  307.417857
min    30.000000  2020-12-01 00:00:00   90.000000  101.000000  195.100000
25%    60.000000  2020-12-08 06:00:00  100.000000  120.750000  250.525000
50%    60.000000  2020-12-15 12:00:00  103.000000  128.500000  300.000000
75%    60.000000  2020-12-23 18:00:00  107.500000  132.750000  350.025000
max    60.000000  2020-12-31 00:00:00  130.000000  175.000000  479.000000
std     7.812457                  NaN    8.042702   13.215325   67.412594

/tmp/ipython-input-1884162814.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Trainer'].fillna('Unknown', inplace=True)

In [ ]:
# Convert Trainer names to Title Case
df['Trainer'] = df['Trainer'].str.title()

# Filter trainers containing 'Alex'
print("Trainers containing 'Alex':")
print(df[df['Trainer'].str.contains('Alex', case=False, na=False)], "\n")

# Convert to lowercase
df['Trainer'] = df['Trainer'].str.lower()
print("Lowercase Trainer names:")
print(df.head(), "\n")

# Convert to uppercase
df['Trainer'] = df['Trainer'].str.upper()
print("Uppercase Trainer names:")
print(df.head(), "\n")

# Filter trainers starting with 'A'
print("Trainers starting with A:")
print(df[df['Trainer'].str.startswith('A', na=False)], "\n")

# Get length of each Trainer name (number of characters)
df['Trainer_Length'] = df['Trainer'].str.len()
print("Trainer name lengths:")
print(df[['Trainer', 'Trainer_Length']])

Trainers containing 'Alex':
   Duration       Date  Pulse  Max_Pulse  Calories  PulseRange Trainer_x  \
0        60 2020-12-01    110        130     409.1  (100, 110]      Alex

  Trainer_y Trainer
0      Alex    Alex

Lowercase Trainer names:
   Duration       Date  Pulse  Max_Pulse  Calories  PulseRange Trainer_x  \
0        60 2020-12-01    110        130     409.1  (100, 110]      Alex
1        60 2020-12-02    117        145     479.0  (110, 120]    Jordan
2        60 2020-12-03    103        135     340.0  (100, 110]    Taylor
3        45 2020-12-04    109        175     282.4  (100, 110]   Unknown
4        45 2020-12-05    117        148     406.0  (110, 120]   Unknown

  Trainer_y  Trainer
0      Alex     alex
1    Jordan   jordan
2    Taylor   taylor
3       NaN  unknown
4       NaN  unknown

Uppercase Trainer names:
   Duration       Date  Pulse  Max_Pulse  Calories  PulseRange Trainer_x  \
0        60 2020-12-01    110        130     409.1  (100, 110]      Alex
1        60 2020-12-02    117        145     479.0  (110, 120]    Jordan
2        60 2020-12-03    103        135     340.0  (100, 110]    Taylor
3        45 2020-12-04    109        175     282.4  (100, 110]   Unknown
4        45 2020-12-05    117        148     406.0  (110, 120]   Unknown

  Trainer_y  Trainer
0      Alex     ALEX
1    Jordan   JORDAN
2    Taylor   TAYLOR
3       NaN  UNKNOWN
4       NaN  UNKNOWN

Trainers starting with A:
   Duration       Date  Pulse  Max_Pulse  Calories  PulseRange Trainer_x  \
0        60 2020-12-01    110        130     409.1  (100, 110]      Alex

  Trainer_y Trainer
0      Alex    ALEX

Trainer name lengths:
    Trainer  Trainer_Length
0      ALEX               4
1    JORDAN               6
2    TAYLOR               6
3   UNKNOWN               7
4   UNKNOWN               7
5   UNKNOWN               7
6   UNKNOWN               7
7   UNKNOWN               7
8   UNKNOWN               7
9   UNKNOWN               7
10  UNKNOWN               7
11  UNKNOWN               7
12  UNKNOWN               7
13  UNKNOWN               7
14  UNKNOWN               7
15  UNKNOWN               7
16  UNKNOWN               7
17  UNKNOWN               7
18  UNKNOWN               7
19  UNKNOWN               7
20  UNKNOWN               7
21  UNKNOWN               7
22  UNKNOWN               7
23  UNKNOWN               7
24  UNKNOWN               7
25  UNKNOWN               7
26  UNKNOWN               7
27  UNKNOWN               7
28  UNKNOWN               7
29  UNKNOWN               7

import kagglehub

# Download latest version
path = kagglehub.dataset_download("vijayuv/onlineretail")

print("Path to dataset files:", path)